{
 "title": "Workstation Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{chip}}" }
   ]
  },
  {
   "title": "Device Cooling State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cooling_device_cur_state{instance=\"pjds-ubuntu\"} ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Disk IO Now",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "{{device}}" }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "ZFS Available Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "zfs_dataset_available_bytes{instance=\"192.168.2.109:9134\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ZFS Pool Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_health{instance=\"192.168.2.109:9134\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "TCP In Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "TCP In Errors 1h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_InErrs{instance=\"pjds-ubuntu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Out Resets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "node_netstat_Tcp_OutRsts", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Load Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Active Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"pjds-ubuntu\"}",
     "legendFormat": "Memory Active Bytes"
    }
   ]
  },
  {
   "title": "CPU Hertz",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Mapped Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_Mapped_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Huge Pages Free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Huge Pages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_HugePages_Free", "legendFormat": "__auto" }
   ]
  }
 ]
}